CREATE DATABASE IF NOT EXISTS storeOOP
	DEFAULT CHARACTER SET utf8mb4
	DEFAULT COLLATE utf8mb4_0900_ai_ci;
	
CREATE USER IF NOT EXISTS 'storeuser'@'localhost' IDENTIFIED BY 'rootroot';
GRANT ALL PRIVILEGES ON storeOOP.* TO 'storeuser'@'localhost';
FLUSH PRIVILEGES;
